context:
  version: "0.2.0"

package:
  name: georaffer
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/georaffer/georaffer-${{ version }}.tar.gz
  sha256: f1b103ae7ab641c172017e00756166c4e7e5fc70f57ed9aea2853d405e572013

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - georaffer = georaffer.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - requests >=2.20
    - truststore >=0.10
    - laspy >=2.0
    - lazrs-python >=0.7
    - numpy >=1.20
    - numba >=0.62
    - pillow >=9.0
    - rasterio >=1.2
    - utm >=0.7
    - tqdm >=4.0

tests:
  - python:
      imports:
        - georaffer
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - georaffer --help

about:
  homepage: https://github.com/michaelschleiss/georaffer
  license: MIT
  license_file: LICENSE
  summary: Download and process geospatial tiles (JP2, LAZ) from German state geodata providers

extra:
  recipe-maintainers:
    - michaelschleiss
